server:
  port: 8080

spring:
  mail:
    host: smtp.example.com
    port: 587
    username: your_username
    password: your_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


notify:
  feishu:
    enabled: true
    webhook-url: https://open.feishu.cn/open-apis/bot/v2/hook/你的token

  dingtalk:
    enabled: true
    webhook-url: https://oapi.dingtalk.com/robot/send?access_token=你的token
    secret:

  mail:
    enabled: false
    from: no-reply@example.com
    to:
      - dev-team@example.com
